apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq
  labels:
    app: vpromq
spec:
  selector:
    matchLabels:
      app: vpromq
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromq
    spec:
      containers: # Đã lùi vào 6 khoảng trắng (con của spec)
        - name: vpromq
          image: rabbitmq:3-management # Khuyên dùng bản management để có giao diện web quản lý
          ports:
            - name: vpromq-port
              containerPort: 5672
          env: # Đã chuyển vào trong container và thẳng hàng với ports, image
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef: # Đã sửa thụt lề cho name và key bên dưới
                  name: app-secret
                  key: rmq-pass
